#!/usr/bin/awk -f
BEGIN {

  countreceived1=0
latency1=0
  countreceived2=0
latency2=0
}
{
  if($1 == "-" && $3 == "0" && $4 == "1" && $5 == "tcp" && $9 == "0.0" && $10 == "3.0")
  {
  starttime1[$11] = $2
  }
  if($1 == "-" && $3 == "4" && $4 == "1" && $5 == "tcp" && $9 == "4.0" && $10 == "5.0")
  {
  starttime2[$11] = $2
  }	

  if($1 == "r" && $3 == "1" && $4 == "0" && $5 == "ack" && $9 == "3.0" && $10 == "0.0")
  {
  countreceived1++
  endtime1[$11] = $2
  latency1=latency1+(endtime1[$11] - starttime1[$11])
  }

  if($1 == "r" && $3 == "1" && $4 == "4" && $5 == "ack" && $9 == "5.0" && $10 == "4.0")
  {
  countreceived2++
  endtime2[$11] = $2
  latency2=latency2+(endtime2[$11] - starttime2[$11])
  }



}
END {
printf("%f\t%f", latency1*1000/countreceived1, latency2*1000/countreceived2);
}

